package provider

import (
	"context"
	"fmt"
	"net/url"
	"reflect"
	"strings"

	"github.com/hashicorp/terraform-plugin-sdk/v2/diag"
	"github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema"
	"github.com/hashicorp/terraform-plugin-sdk/v2/helper/validation"
)

var collectorTargetKinds = []string{
	"postgres", "mysql", "redis", "mongodb", "memcached", "elasticsearch",
	"nginx", "apache", "kafka", "prometheus",
}

var collectorTargetProcessKinds = map[string]bool{
	"nginx":      true,
	"apache":     true,
	"kafka":      true,
	"prometheus": true,
}

var collectorTargetSchema = map[string]*schema.Schema{
	"id": {
		Description: "The ID of this target.",
		Type:        schema.TypeString,
		Computed:    true,
	},
	"collector_id": {
		Description: "The ID of the collector this target belongs to.",
		Type:        schema.TypeString,
		Required:    true,
		ForceNew:    true,
	},
	"kind": {
		Description:  fmt.Sprintf("The target kind. One of: %s.", strings.Join(collectorTargetKinds, ", ")),
		Type:         schema.TypeString,
		Required:     true,
		ForceNew:     true,
		ValidateFunc: validation.StringInSlice(collectorTargetKinds, false),
	},
	"host": {
		Description: "Hostname or IP of the database server. Use this for database kinds (postgres, mysql, redis, mongodb, memcached, elasticsearch). For process kinds use `collector_host` instead.",
		Type:        schema.TypeString,
		Optional:    true,
	},
	"collector_host": {
		Description: "Hostname of the collector host running this process. Use this for process kinds (nginx, apache, kafka, prometheus). Must match the hostname of a `collector_host` reporting to this collector. For database kinds use `host` instead.",
		Type:        schema.TypeString,
		Optional:    true,
	},
	"port": {
		Description: "Port the target listens on. Required for database kinds and most process kinds; not used by prometheus (use `endpoint` instead).",
		Type:        schema.TypeInt,
		Optional:    true,
	},
	"service": {
		Description: "Friendly name for the target. Required for process kinds.",
		Type:        schema.TypeString,
		Optional:    true,
	},
	"listen_ip": {
		Description: "IP address the process listens on, as seen from the collector host. Used for nginx, apache, kafka.",
		Type:        schema.TypeString,
		Optional:    true,
	},
	"endpoint": {
		Description: "Full scrape URL. Required for prometheus.",
		Type:        schema.TypeString,
		Optional:    true,
	},
	"scheme": {
		Description:  "URL scheme. Required for elasticsearch. Valid values: `http`, `https`.",
		Type:         schema.TypeString,
		Optional:     true,
		ValidateFunc: validation.StringInSlice([]string{"http", "https"}, false),
	},
	"username": {
		Description: "Username for authentication. Used by database kinds.",
		Type:        schema.TypeString,
		Optional:    true,
	},
	"password": {
		Description: "Password for authentication. Used by database kinds.",
		Type:        schema.TypeString,
		Optional:    true,
		Sensitive:   true,
	},
	"api_key": {
		Description: "API key for authentication. Used by elasticsearch.",
		Type:        schema.TypeString,
		Optional:    true,
		Sensitive:   true,
	},
	"ssl_mode": {
		Description:  "SSL mode. Required for postgres-family kinds. Valid values: `disable`, `require`, `verify-ca`.",
		Type:         schema.TypeString,
		Optional:     true,
		ValidateFunc: validation.StringInSlice([]string{"disable", "require", "verify-ca"}, false),
	},
	"tls": {
		Description:  "TLS mode. Required for mysql. Valid values: `false`, `true`, `skip-verify`, `preferred`.",
		Type:         schema.TypeString,
		Optional:     true,
		ValidateFunc: validation.StringInSlice([]string{"false", "true", "skip-verify", "preferred"}, false),
	},
	"enabled": {
		Description: "Whether the collector should scrape this target. Defaults to `true`. Setting to `false` puts the target into `disabled` status — it remains configured but is not scraped.",
		Type:        schema.TypeBool,
		Optional:    true,
		Default:     true,
	},
	"status": {
		Description: "Current status of the target as reported by the collector.",
		Type:        schema.TypeString,
		Computed:    true,
	},
	"autogenerated": {
		Description: "Whether this target was auto-detected by the collector.",
		Type:        schema.TypeBool,
		Computed:    true,
	},
	"paused_until": {
		Description: "If set, the target is in backoff until this time.",
		Type:        schema.TypeString,
		Computed:    true,
	},
	"consecutive_failure_count": {
		Description: "Number of consecutive scrape failures for this target.",
		Type:        schema.TypeInt,
		Computed:    true,
	},
	"last_ping_at": {
		Description: "Last time the target was successfully scraped.",
		Type:        schema.TypeString,
		Computed:    true,
	},
	"container": {
		Description: "Container the target was detected in, if any.",
		Type:        schema.TypeString,
		Computed:    true,
	},
	"detected_host": {
		Description: "Host the target was detected on, if any.",
		Type:        schema.TypeString,
		Computed:    true,
	},
	"created_at": {
		Description: "The time when this target was created.",
		Type:        schema.TypeString,
		Computed:    true,
	},
	"updated_at": {
		Description: "The time when this target was last updated.",
		Type:        schema.TypeString,
		Computed:    true,
	},
}

type collectorTarget struct {
	Kind                    *string `json:"kind,omitempty"`
	Host                    *string `json:"host,omitempty"`
	Port                    *int    `json:"port,omitempty"`
	Service                 *string `json:"service,omitempty"`
	ListenIP                *string `json:"listen_ip,omitempty"`
	Endpoint                *string `json:"endpoint,omitempty"`
	Scheme                  *string `json:"scheme,omitempty"`
	Username                *string `json:"username,omitempty"`
	Password                *string `json:"password,omitempty"`
	APIKey                  *string `json:"api_key,omitempty"`
	SSLMode                 *string `json:"ssl_mode,omitempty"`
	TLS                     *string `json:"tls,omitempty"`
	Enabled                 *bool   `json:"enabled,omitempty"`
	Status                  *string `json:"status,omitempty"`
	Autogenerated           *bool   `json:"autogenerated,omitempty"`
	PausedUntil             *string `json:"paused_until,omitempty"`
	ConsecutiveFailureCount *int    `json:"consecutive_failure_count,omitempty"`
	LastPingAt              *string `json:"last_ping_at,omitempty"`
	Container               *string `json:"container,omitempty"`
	DetectedHost            *string `json:"detected_host,omitempty"`
	CreatedAt               *string `json:"created_at,omitempty"`
	UpdatedAt               *string `json:"updated_at,omitempty"`
}

type collectorTargetHTTPResponse struct {
	Data struct {
		ID         string          `json:"id"`
		Attributes collectorTarget `json:"attributes"`
	} `json:"data"`
}

func newCollectorTargetResource() *schema.Resource {
	return &schema.Resource{
		CreateContext: collectorTargetCreate,
		ReadContext:   collectorTargetRead,
		UpdateContext: collectorTargetUpdate,
		DeleteContext: collectorTargetDelete,
		Importer: &schema.ResourceImporter{
			StateContext: collectorTargetImport,
		},
		CustomizeDiff: validateCollectorTarget,
		Description:   "Manages a single 'Collect metrics' target on a Better Stack Collector — a database (postgres, mysql, redis, mongodb, memcached, elasticsearch) or process exporter (nginx, apache, kafka, prometheus) that the collector scrapes.",
		Schema:        collectorTargetSchema,
	}
}

func validateCollectorTarget(ctx context.Context, diff *schema.ResourceDiff, v interface{}) error {
	kind := diff.Get("kind").(string)
	if kind == "" {
		return nil
	}

	host := diff.Get("host").(string)
	collectorHost := diff.Get("collector_host").(string)
	service := diff.Get("service").(string)
	endpoint := diff.Get("endpoint").(string)
	scheme := diff.Get("scheme").(string)

	if collectorTargetProcessKinds[kind] {
		if collectorHost == "" {
			return fmt.Errorf("collector_host is required for process kind %q", kind)
		}
		if host != "" {
			return fmt.Errorf("host is for database kinds; use collector_host for process kind %q", kind)
		}
		if service == "" {
			return fmt.Errorf("service is required for process kind %q", kind)
		}
		if kind == "prometheus" && endpoint == "" {
			return fmt.Errorf("endpoint is required for prometheus")
		}
	} else {
		if host == "" {
			return fmt.Errorf("host is required for kind %q", kind)
		}
		if collectorHost != "" {
			return fmt.Errorf("collector_host is for process kinds; use host for kind %q", kind)
		}
		if kind == "elasticsearch" && scheme == "" {
			return fmt.Errorf("scheme is required for elasticsearch")
		}
	}

	return nil
}

func collectorTargetCollectionURL(collectorID string) string {
	return fmt.Sprintf("/api/v1/collectors/%s/targets", url.PathEscape(collectorID))
}

func collectorTargetMemberURL(collectorID, id string) string {
	return fmt.Sprintf("/api/v1/collectors/%s/targets/%s", url.PathEscape(collectorID), url.PathEscape(id))
}

func collectorTargetBuildRequest(d *schema.ResourceData, includeKind bool) collectorTarget {
	var in collectorTarget
	kind := d.Get("kind").(string)
	if includeKind {
		in.Kind = stringPtr(kind)
	}

	if collectorTargetProcessKinds[kind] {
		if v := d.Get("collector_host").(string); v != "" {
			in.Host = stringPtr(v)
		}
	} else {
		if v := d.Get("host").(string); v != "" {
			in.Host = stringPtr(v)
		}
	}

	if v, ok := d.GetOk("port"); ok {
		p := v.(int)
		in.Port = &p
	}
	if v := d.Get("service").(string); v != "" {
		in.Service = stringPtr(v)
	}
	if v := d.Get("listen_ip").(string); v != "" {
		in.ListenIP = stringPtr(v)
	}
	if v := d.Get("endpoint").(string); v != "" {
		in.Endpoint = stringPtr(v)
	}
	if v := d.Get("scheme").(string); v != "" {
		in.Scheme = stringPtr(v)
	}
	if v := d.Get("username").(string); v != "" {
		in.Username = stringPtr(v)
	}
	if v := d.Get("password").(string); v != "" {
		in.Password = stringPtr(v)
	}
	if v := d.Get("api_key").(string); v != "" {
		in.APIKey = stringPtr(v)
	}
	if v := d.Get("ssl_mode").(string); v != "" {
		in.SSLMode = stringPtr(v)
	}
	if v := d.Get("tls").(string); v != "" {
		in.TLS = stringPtr(v)
	}

	enabled := boolFromResourceData(d, "enabled")
	if enabled != nil {
		in.Enabled = enabled
	}

	return in
}

func collectorTargetCreate(ctx context.Context, d *schema.ResourceData, meta interface{}) diag.Diagnostics {
	collectorID := d.Get("collector_id").(string)
	in := collectorTargetBuildRequest(d, true)

	var out collectorTargetHTTPResponse
	if err := resourceCreate(ctx, meta, collectorTargetCollectionURL(collectorID), &in, &out); err != nil {
		return err
	}
	d.SetId(out.Data.ID)

	return collectorTargetCopyAttrs(d, &out.Data.Attributes)
}

func collectorTargetRead(ctx context.Context, d *schema.ResourceData, meta interface{}) diag.Diagnostics {
	collectorID := d.Get("collector_id").(string)
	var out collectorTargetHTTPResponse
	err, ok := resourceReadWithBaseURL(ctx, meta, meta.(*client).TelemetryBaseURL(), collectorTargetMemberURL(collectorID, d.Id()), &out)
	if err != nil {
		return err
	}
	if !ok {
		d.SetId("")
		return nil
	}

	return collectorTargetCopyAttrs(d, &out.Data.Attributes)
}

func collectorTargetUpdate(ctx context.Context, d *schema.ResourceData, meta interface{}) diag.Diagnostics {
	collectorID := d.Get("collector_id").(string)
	in := collectorTargetBuildRequest(d, false)
	return resourceUpdate(ctx, meta, collectorTargetMemberURL(collectorID, d.Id()), &in)
}

func collectorTargetDelete(ctx context.Context, d *schema.ResourceData, meta interface{}) diag.Diagnostics {
	collectorID := d.Get("collector_id").(string)
	return resourceDelete(ctx, meta, collectorTargetMemberURL(collectorID, d.Id()))
}

// Import format: <collector_id>:<target_id>
func collectorTargetImport(ctx context.Context, d *schema.ResourceData, meta interface{}) ([]*schema.ResourceData, error) {
	parts := strings.SplitN(d.Id(), ":", 2)
	if len(parts) != 2 || parts[0] == "" || parts[1] == "" {
		return nil, fmt.Errorf("import id must be in the form <collector_id>:<target_id>, got %q", d.Id())
	}
	if err := d.Set("collector_id", parts[0]); err != nil {
		return nil, err
	}
	d.SetId(parts[1])
	return []*schema.ResourceData{d}, nil
}

func collectorTargetCopyAttrs(d *schema.ResourceData, in *collectorTarget) diag.Diagnostics {
	var derr diag.Diagnostics
	kind := ""
	if in.Kind != nil {
		kind = *in.Kind
	}

	scalarFields := []struct {
		k string
		v interface{}
	}{
		{"kind", in.Kind},
		{"port", in.Port},
		{"service", in.Service},
		{"listen_ip", in.ListenIP},
		{"endpoint", in.Endpoint},
		{"scheme", in.Scheme},
		{"username", in.Username},
		{"ssl_mode", in.SSLMode},
		{"tls", in.TLS},
		{"enabled", in.Enabled},
		{"status", in.Status},
		{"autogenerated", in.Autogenerated},
		{"paused_until", in.PausedUntil},
		{"consecutive_failure_count", in.ConsecutiveFailureCount},
		{"last_ping_at", in.LastPingAt},
		{"container", in.Container},
		{"detected_host", in.DetectedHost},
		{"created_at", in.CreatedAt},
		{"updated_at", in.UpdatedAt},
	}
	for _, f := range scalarFields {
		val := reflect.ValueOf(f.v)
		if !val.IsValid() || val.IsNil() {
			continue
		}
		if err := d.Set(f.k, reflect.Indirect(val).Interface()); err != nil {
			derr = append(derr, diag.FromErr(err)[0])
		}
	}

	hostValue := ""
	if in.Host != nil {
		hostValue = *in.Host
	}
	if collectorTargetProcessKinds[kind] {
		if err := d.Set("collector_host", hostValue); err != nil {
			derr = append(derr, diag.FromErr(err)[0])
		}
		if err := d.Set("host", ""); err != nil {
			derr = append(derr, diag.FromErr(err)[0])
		}
	} else {
		if err := d.Set("host", hostValue); err != nil {
			derr = append(derr, diag.FromErr(err)[0])
		}
		if err := d.Set("collector_host", ""); err != nil {
			derr = append(derr, diag.FromErr(err)[0])
		}
	}

	if existing := d.Get("password").(string); existing != "" {
		if err := d.Set("password", existing); err != nil {
			derr = append(derr, diag.FromErr(err)[0])
		}
	}
	if existing := d.Get("api_key").(string); existing != "" {
		if err := d.Set("api_key", existing); err != nil {
			derr = append(derr, diag.FromErr(err)[0])
		}
	}

	return derr
}
