package provider

import (
	"encoding/json"
	"fmt"
	"io"
	"net/http"
	"net/http/httptest"
	"regexp"
	"sync/atomic"
	"testing"

	"github.com/hashicorp/terraform-plugin-sdk/v2/helper/resource"
	"github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema"
	"github.com/hashicorp/terraform-plugin-sdk/v2/terraform"
)

func newCollectorTargetMockServer(t *testing.T, collectorID, id string) (*httptest.Server, *atomic.Value) {
	var data atomic.Value
	server := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		if r.Header.Get("Authorization") != "Bearer foo" {
			t.Fatal("Not authorized: " + r.Header.Get("Authorization"))
		}

		prefix := fmt.Sprintf("/api/v1/collectors/%s/targets", collectorID)

		switch {
		case r.Method == http.MethodPost && r.RequestURI == prefix:
			body, err := io.ReadAll(r.Body)
			if err != nil {
				t.Fatal(err)
			}
			// The real API does not return password/api_key — strip them on the create response.
			stripped := stripSecretsFromBody(t, body)
			stripped = inject(t, stripped, "status", "pending")
			stripped = inject(t, stripped, "autogenerated", false)
			stripped = inject(t, stripped, "enabled", true)
			stripped = inject(t, stripped, "created_at", "2026-05-19T10:00:00.000Z")
			stripped = inject(t, stripped, "updated_at", "2026-05-19T10:00:00.000Z")
			data.Store(stripped)
			w.WriteHeader(http.StatusCreated)
			_, _ = w.Write([]byte(fmt.Sprintf(`{"data":{"id":%q,"attributes":%s}}`, id, stripped)))

		case r.Method == http.MethodGet && r.RequestURI == prefix+"/"+id:
			_, _ = w.Write([]byte(fmt.Sprintf(`{"data":{"id":%q,"attributes":%s}}`, id, data.Load().([]byte))))

		case r.Method == http.MethodPatch && r.RequestURI == prefix+"/"+id:
			body, err := io.ReadAll(r.Body)
			if err != nil {
				t.Fatal(err)
			}
			patch := make(map[string]interface{})
			if err = json.Unmarshal(data.Load().([]byte), &patch); err != nil {
				t.Fatal(err)
			}
			if err = json.Unmarshal(body, &patch); err != nil {
				t.Fatal(err)
			}
			patched, err := json.Marshal(patch)
			if err != nil {
				t.Fatal(err)
			}
			patched = stripSecretsFromBody(t, patched)
			data.Store(patched)
			_, _ = w.Write([]byte(fmt.Sprintf(`{"data":{"id":%q,"attributes":%s}}`, id, patched)))

		case r.Method == http.MethodDelete && r.RequestURI == prefix+"/"+id:
			w.WriteHeader(http.StatusNoContent)
			data.Store([]byte(nil))

		default:
			t.Fatalf("Unexpected %s %s", r.Method, r.RequestURI)
		}
	}))
	return server, &data
}

func stripSecretsFromBody(t *testing.T, body []byte) []byte {
	m := make(map[string]interface{})
	if err := json.Unmarshal(body, &m); err != nil {
		t.Fatal(err)
	}
	delete(m, "password")
	delete(m, "api_key")
	out, err := json.Marshal(m)
	if err != nil {
		t.Fatal(err)
	}
	return out
}

func TestResourceCollectorTargetDatabase(t *testing.T) {
	server, _ := newCollectorTargetMockServer(t, "77", "5")
	defer server.Close()

	resource.Test(t, resource.TestCase{
		IsUnitTest: true,
		ProviderFactories: map[string]func() (*schema.Provider, error){
			"logtail": func() (*schema.Provider, error) {
				return New(WithURL(server.URL)), nil
			},
		},
		Steps: []resource.TestStep{
			// Step 1: create with credentials.
			{
				Config: `
				provider "logtail" {
					api_token = "foo"
				}

				resource "logtail_collector_target" "db" {
					collector_id = "77"
					kind         = "postgres"
					host         = "db.example.com"
					port         = 5432
					username     = "monitor"
					password     = "secret"
					ssl_mode     = "require"
				}
				`,
				Check: resource.ComposeTestCheckFunc(
					resource.TestCheckResourceAttrSet("logtail_collector_target.db", "id"),
					resource.TestCheckResourceAttr("logtail_collector_target.db", "collector_id", "77"),
					resource.TestCheckResourceAttr("logtail_collector_target.db", "kind", "postgres"),
					resource.TestCheckResourceAttr("logtail_collector_target.db", "host", "db.example.com"),
					resource.TestCheckResourceAttr("logtail_collector_target.db", "port", "5432"),
					resource.TestCheckResourceAttr("logtail_collector_target.db", "username", "monitor"),
					// Password preserved from config across the API round-trip (API does not return it).
					resource.TestCheckResourceAttr("logtail_collector_target.db", "password", "secret"),
					resource.TestCheckResourceAttr("logtail_collector_target.db", "ssl_mode", "require"),
					resource.TestCheckResourceAttr("logtail_collector_target.db", "enabled", "true"),
					resource.TestCheckResourceAttr("logtail_collector_target.db", "status", "pending"),
					resource.TestCheckResourceAttr("logtail_collector_target.db", "collector_host", ""),
				),
			},
			// Step 2: update host — triggers PATCH; credentials untouched.
			{
				Config: `
				provider "logtail" {
					api_token = "foo"
				}

				resource "logtail_collector_target" "db" {
					collector_id = "77"
					kind         = "postgres"
					host         = "db-new.example.com"
					port         = 5432
					username     = "monitor"
					password     = "secret"
					ssl_mode     = "require"
				}
				`,
				Check: resource.ComposeTestCheckFunc(
					resource.TestCheckResourceAttr("logtail_collector_target.db", "host", "db-new.example.com"),
					resource.TestCheckResourceAttr("logtail_collector_target.db", "password", "secret"),
				),
			},
			// Step 3: flip enabled false — PATCH-only.
			{
				Config: `
				provider "logtail" {
					api_token = "foo"
				}

				resource "logtail_collector_target" "db" {
					collector_id = "77"
					kind         = "postgres"
					host         = "db-new.example.com"
					port         = 5432
					username     = "monitor"
					password     = "secret"
					ssl_mode     = "require"
					enabled      = false
				}
				`,
				Check: resource.ComposeTestCheckFunc(
					resource.TestCheckResourceAttr("logtail_collector_target.db", "enabled", "false"),
				),
			},
			// Step 4: import via "<collector_id>:<target_id>" format.
			{
				ResourceName:      "logtail_collector_target.db",
				ImportState:       true,
				ImportStateVerify: true,
				ImportStateIdFunc: func(s *terraform.State) (string, error) {
					return "77:5", nil
				},
				// API never returns the password — TF state has it from config, imported state does not.
				ImportStateVerifyIgnore: []string{"password"},
			},
		},
	})
}

func TestResourceCollectorTargetElasticsearch(t *testing.T) {
	server, _ := newCollectorTargetMockServer(t, "77", "7")
	defer server.Close()

	resource.Test(t, resource.TestCase{
		IsUnitTest: true,
		ProviderFactories: map[string]func() (*schema.Provider, error){
			"logtail": func() (*schema.Provider, error) {
				return New(WithURL(server.URL)), nil
			},
		},
		Steps: []resource.TestStep{
			{
				Config: `
				provider "logtail" {
					api_token = "foo"
				}

				resource "logtail_collector_target" "es" {
					collector_id = "77"
					kind         = "elasticsearch"
					host         = "es.example.com"
					port         = 9200
					scheme       = "https"
					api_key      = "es-secret"
				}
				`,
				Check: resource.ComposeTestCheckFunc(
					resource.TestCheckResourceAttr("logtail_collector_target.es", "kind", "elasticsearch"),
					resource.TestCheckResourceAttr("logtail_collector_target.es", "scheme", "https"),
					// api_key never returned by API; TF state preserves config value.
					resource.TestCheckResourceAttr("logtail_collector_target.es", "api_key", "es-secret"),
				),
			},
		},
	})
}

func TestResourceCollectorTargetProcess(t *testing.T) {
	server, _ := newCollectorTargetMockServer(t, "77", "9")
	defer server.Close()

	resource.Test(t, resource.TestCase{
		IsUnitTest: true,
		ProviderFactories: map[string]func() (*schema.Provider, error){
			"logtail": func() (*schema.Provider, error) {
				return New(WithURL(server.URL)), nil
			},
		},
		Steps: []resource.TestStep{
			{
				Config: `
				provider "logtail" {
					api_token = "foo"
				}

				resource "logtail_collector_target" "prom" {
					collector_id   = "77"
					kind           = "prometheus"
					service        = "my-app"
					collector_host = "app-1.internal"
					endpoint       = "http://10.0.0.5:9090/metrics"
				}
				`,
				Check: resource.ComposeTestCheckFunc(
					resource.TestCheckResourceAttr("logtail_collector_target.prom", "kind", "prometheus"),
					resource.TestCheckResourceAttr("logtail_collector_target.prom", "service", "my-app"),
					resource.TestCheckResourceAttr("logtail_collector_target.prom", "collector_host", "app-1.internal"),
					resource.TestCheckResourceAttr("logtail_collector_target.prom", "endpoint", "http://10.0.0.5:9090/metrics"),
					resource.TestCheckResourceAttr("logtail_collector_target.prom", "host", ""),
				),
			},
		},
	})
}

func TestResourceCollectorTargetDrift(t *testing.T) {
	// Simulates external edit: API returns host different from what TF set.
	var data atomic.Value

	server := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		if r.Header.Get("Authorization") != "Bearer foo" {
			t.Fatal("Not authorized")
		}
		prefix := "/api/v1/collectors/77/targets"
		id := "5"
		switch {
		case r.Method == http.MethodPost && r.RequestURI == prefix:
			body, _ := io.ReadAll(r.Body)
			body = inject(t, body, "status", "pending")
			body = inject(t, body, "enabled", true)
			body = inject(t, body, "autogenerated", false)
			data.Store(body)
			w.WriteHeader(http.StatusCreated)
			_, _ = w.Write([]byte(fmt.Sprintf(`{"data":{"id":%q,"attributes":%s}}`, id, body)))
		case r.Method == http.MethodGet && r.RequestURI == prefix+"/"+id:
			// Simulate drift: someone changed the host externally.
			drifted := inject(t, data.Load().([]byte), "host", "externally-changed.example.com")
			_, _ = w.Write([]byte(fmt.Sprintf(`{"data":{"id":%q,"attributes":%s}}`, id, drifted)))
		case r.Method == http.MethodDelete && r.RequestURI == prefix+"/"+id:
			w.WriteHeader(http.StatusNoContent)
		case r.Method == http.MethodPatch:
			t.Fatal("unexpected PATCH")
		default:
			t.Fatalf("Unexpected %s %s", r.Method, r.RequestURI)
		}
	}))
	defer server.Close()

	resource.Test(t, resource.TestCase{
		IsUnitTest: true,
		ProviderFactories: map[string]func() (*schema.Provider, error){
			"logtail": func() (*schema.Provider, error) {
				return New(WithURL(server.URL)), nil
			},
		},
		Steps: []resource.TestStep{
			{
				Config: `
				provider "logtail" {
					api_token = "foo"
				}

				resource "logtail_collector_target" "db" {
					collector_id = "77"
					kind         = "redis"
					host         = "r.example.com"
					port         = 6379
				}
				`,
				// Post-apply refresh fetches drifted state from the API; replan must surface a non-empty diff.
				ExpectNonEmptyPlan: true,
			},
		},
	})
}

func TestResourceCollectorTargetMissingFromAPI(t *testing.T) {
	// API returns 404 on subsequent reads — resource should be reaped from state.
	created := false
	server := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		if r.Header.Get("Authorization") != "Bearer foo" {
			t.Fatal("Not authorized")
		}
		prefix := "/api/v1/collectors/77/targets"
		id := "5"
		switch {
		case r.Method == http.MethodPost && r.RequestURI == prefix:
			body, _ := io.ReadAll(r.Body)
			body = inject(t, body, "status", "pending")
			body = inject(t, body, "enabled", true)
			body = inject(t, body, "autogenerated", false)
			created = true
			w.WriteHeader(http.StatusCreated)
			_, _ = w.Write([]byte(fmt.Sprintf(`{"data":{"id":%q,"attributes":%s}}`, id, body)))
		case r.Method == http.MethodGet && r.RequestURI == prefix+"/"+id:
			if !created {
				t.Fatal("GET before POST")
			}
			w.WriteHeader(http.StatusNotFound)
		case r.Method == http.MethodDelete && r.RequestURI == prefix+"/"+id:
			w.WriteHeader(http.StatusNoContent)
		default:
			t.Fatalf("Unexpected %s %s", r.Method, r.RequestURI)
		}
	}))
	defer server.Close()

	resource.Test(t, resource.TestCase{
		IsUnitTest: true,
		ProviderFactories: map[string]func() (*schema.Provider, error){
			"logtail": func() (*schema.Provider, error) {
				return New(WithURL(server.URL)), nil
			},
		},
		Steps: []resource.TestStep{
			{
				Config: `
				provider "logtail" {
					api_token = "foo"
				}

				resource "logtail_collector_target" "db" {
					collector_id = "77"
					kind         = "redis"
					host         = "r.example.com"
					port         = 6379
				}
				`,
				// Refresh sees 404 → resource is removed from state → plan recreates it.
				ExpectNonEmptyPlan: true,
			},
		},
	})
}

func TestResourceCollectorTargetValidation(t *testing.T) {
	cases := []struct {
		name    string
		config  string
		errorRe string
	}{
		{
			name: "process kind without collector_host",
			config: `
			resource "logtail_collector_target" "x" {
				collector_id = "1"
				kind         = "nginx"
				service      = "my-nginx"
				listen_ip    = "10.0.0.1"
				port         = 80
			}
			`,
			errorRe: `collector_host is required for process kind "nginx"`,
		},
		{
			name: "process kind with database `host` (not allowed)",
			config: `
			resource "logtail_collector_target" "x" {
				collector_id   = "1"
				kind           = "nginx"
				service        = "my-nginx"
				host           = "wrong-place.internal"
				collector_host = "right-place.internal"
				listen_ip      = "10.0.0.1"
				port           = 80
			}
			`,
			errorRe: `host is for database kinds`,
		},
		{
			name: "process kind without service",
			config: `
			resource "logtail_collector_target" "x" {
				collector_id   = "1"
				kind           = "nginx"
				collector_host = "h"
				listen_ip      = "10.0.0.1"
				port           = 80
			}
			`,
			errorRe: `service is required for process kind "nginx"`,
		},
		{
			name: "database kind without host",
			config: `
			resource "logtail_collector_target" "x" {
				collector_id = "1"
				kind         = "redis"
				port         = 6379
			}
			`,
			errorRe: `host is required for kind "redis"`,
		},
		{
			name: "database kind with collector_host (not allowed)",
			config: `
			resource "logtail_collector_target" "x" {
				collector_id   = "1"
				kind           = "redis"
				host           = "r.example.com"
				collector_host = "wrong-here.internal"
				port           = 6379
			}
			`,
			errorRe: `collector_host is for process kinds`,
		},
		{
			name: "prometheus without endpoint",
			config: `
			resource "logtail_collector_target" "x" {
				collector_id   = "1"
				kind           = "prometheus"
				service        = "my-app"
				collector_host = "h"
			}
			`,
			errorRe: `endpoint is required for prometheus`,
		},
		{
			name: "elasticsearch without scheme",
			config: `
			resource "logtail_collector_target" "x" {
				collector_id = "1"
				kind         = "elasticsearch"
				host         = "es.example.com"
				port         = 9200
			}
			`,
			errorRe: `scheme is required for elasticsearch`,
		},
		{
			name: "unknown kind",
			config: `
			resource "logtail_collector_target" "x" {
				collector_id = "1"
				kind         = "cassandra"
				host         = "c.example.com"
				port         = 9042
			}
			`,
			errorRe: `expected kind to be one of`,
		},
		{
			name: "scheme value out of allowed set",
			config: `
			resource "logtail_collector_target" "x" {
				collector_id = "1"
				kind         = "elasticsearch"
				host         = "es.example.com"
				port         = 9200
				scheme       = "ftp"
			}
			`,
			errorRe: `expected scheme to be one of`,
		},
		{
			name: "ssl_mode value out of allowed set",
			config: `
			resource "logtail_collector_target" "x" {
				collector_id = "1"
				kind         = "postgres"
				host         = "pg.example.com"
				port         = 5432
				ssl_mode     = "pretend-secure"
			}
			`,
			errorRe: `expected ssl_mode to be one of`,
		},
		{
			name: "tls value out of allowed set",
			config: `
			resource "logtail_collector_target" "x" {
				collector_id = "1"
				kind         = "mysql"
				host         = "m.example.com"
				port         = 3306
				tls          = "maybe"
			}
			`,
			errorRe: `expected tls to be one of`,
		},
		{
			name: "missing collector_id",
			config: `
			resource "logtail_collector_target" "x" {
				kind = "redis"
				host = "r.example.com"
				port = 6379
			}
			`,
			errorRe: `The argument "collector_id" is required`,
		},
		{
			name: "missing kind",
			config: `
			resource "logtail_collector_target" "x" {
				collector_id = "1"
				host         = "r.example.com"
				port         = 6379
			}
			`,
			errorRe: `The argument "kind" is required`,
		},
		{
			name: "endpoint on postgres (not valid for kind)",
			config: `
			resource "logtail_collector_target" "x" {
				collector_id = "1"
				kind         = "postgres"
				host         = "pg.example.com"
				port         = 5432
				ssl_mode     = "require"
				endpoint     = "http://does/not/apply"
			}
			`,
			errorRe: `endpoint is not valid for kind "postgres"`,
		},
		{
			name: "scheme on redis (not valid for kind)",
			config: `
			resource "logtail_collector_target" "x" {
				collector_id = "1"
				kind         = "redis"
				host         = "r.example.com"
				port         = 6379
				scheme       = "https"
			}
			`,
			errorRe: `scheme is not valid for kind "redis"`,
		},
		{
			name: "api_key on postgres (not valid for kind)",
			config: `
			resource "logtail_collector_target" "x" {
				collector_id = "1"
				kind         = "postgres"
				host         = "pg.example.com"
				port         = 5432
				ssl_mode     = "require"
				api_key      = "leaked-key"
			}
			`,
			errorRe: `api_key is not valid for kind "postgres"`,
		},
		{
			name: "ssl_mode on mysql (not valid for kind)",
			config: `
			resource "logtail_collector_target" "x" {
				collector_id = "1"
				kind         = "mysql"
				host         = "m.example.com"
				port         = 3306
				tls          = "true"
				ssl_mode     = "require"
			}
			`,
			errorRe: `ssl_mode is not valid for kind "mysql"`,
		},
		{
			name: "tls on postgres (not valid for kind)",
			config: `
			resource "logtail_collector_target" "x" {
				collector_id = "1"
				kind         = "postgres"
				host         = "pg.example.com"
				port         = 5432
				ssl_mode     = "require"
				tls          = "true"
			}
			`,
			errorRe: `tls is not valid for kind "postgres"`,
		},
		{
			name: "listen_ip on redis (not valid for kind)",
			config: `
			resource "logtail_collector_target" "x" {
				collector_id = "1"
				kind         = "redis"
				host         = "r.example.com"
				port         = 6379
				listen_ip    = "10.0.0.1"
			}
			`,
			errorRe: `listen_ip is not valid for kind "redis"`,
		},
		{
			name: "service on redis (not valid for kind)",
			config: `
			resource "logtail_collector_target" "x" {
				collector_id = "1"
				kind         = "redis"
				host         = "r.example.com"
				port         = 6379
				service      = "my-redis"
			}
			`,
			errorRe: `service is not valid for kind "redis"`,
		},
		{
			name: "port on prometheus (not valid for kind)",
			config: `
			resource "logtail_collector_target" "x" {
				collector_id   = "1"
				kind           = "prometheus"
				collector_host = "h"
				service        = "my-app"
				endpoint       = "http://10.0.0.5:9090/metrics"
				port           = 9090
			}
			`,
			errorRe: `port is not valid for kind "prometheus"`,
		},
		{
			name: "username on nginx (not valid for kind)",
			config: `
			resource "logtail_collector_target" "x" {
				collector_id   = "1"
				kind           = "nginx"
				collector_host = "h"
				service        = "my-nginx"
				listen_ip      = "10.0.0.1"
				port           = 80
				username       = "u"
			}
			`,
			errorRe: `username is not valid for kind "nginx"`,
		},
	}

	server := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		t.Fatalf("validation tests should not reach the API: %s %s", r.Method, r.RequestURI)
	}))
	defer server.Close()

	for _, tc := range cases {
		tc := tc
		t.Run(tc.name, func(t *testing.T) {
			resource.Test(t, resource.TestCase{
				IsUnitTest: true,
				ProviderFactories: map[string]func() (*schema.Provider, error){
					"logtail": func() (*schema.Provider, error) {
						return New(WithURL(server.URL)), nil
					},
				},
				Steps: []resource.TestStep{
					{
						Config: `provider "logtail" {
							api_token = "foo"
						}
						` + tc.config,
						ExpectError: regexp.MustCompile(tc.errorRe),
					},
				},
			})
		})
	}
}
